INSERT INTO ide.def_categorias (codigo, nombre, sigla, definicion, id_padre, usuario_crea, fecha_crea) VALUES
('1', 'Categoría ISO 19115', 'ISO19115', 'Es una norma internacional que define un esquema estándar para la creación de metadatos, que son descripciones detalladas de los datos geográficos', 0, 1, '15-08-2025'),
('001', 'Agricultura', 'farming', 'Cría de animales y/o cultivo de plantas. Ejemplos: agricultura, irrigación, acuicultura, plantaciones, plagas, epidemias y enfermedades que afectan a las cosechas y al ganado', 1, 1, '15-08-2025'),
('002', 'Biología', 'biota', 'Flora y fauna en el medio natural. Ejemplos: fauna, vegetación, ciencias biológicas, ecología, vida salvaje, vida marina, pantanos, hábitat', 1, 1, '15-08-2025'),
('003', 'Límites', 'boundaries', 'Descripciones legales del terreno. Ejemplos: límites administrativos y políticos', 1, 1, '15-08-2025'),
('004', 'Atmósfera, Climatología, Meteorología', 'climatologyMeteorologyAtmosphere', 'Procesos y fenómenos de la atmósfera. Ejemplos: cobertura nubosa, tiempo, clima, condiciones atmosféricas, cambio climático, precipitación', 1, 1, '15-08-2025'),
('005', 'Economía', 'economy', 'Actividades económicas, condiciones y empleo. Ejemplos: producción, trabajo, ingresos, comercio, industria, turismo y ecoturismo, silvicultura, políticas pesqueras, caza comercial y de subsistencia, exploración y explotación de recursos tales como minerales, aceite y gas', 1, 1, '15-08-2025'),
('006', 'Elevación', 'elevation', 'Altura sobre o bajo el nivel del mar. Ejemplos: altitud, batimetría, modelos digitales del terreno, pendiente y productos derivados', 1, 1, '15-08-2025'),
('007', 'Medio Ambiente', 'environment', 'Recursos medio ambientales, protección y conservación. Ejemplos: contaminación ambiental, tratamiento y almacenamiento de desechos, valoración del impacto ambiental, monitoreo del riesgo medioambiental, reservas naturales, paisaje', 1, 1, '15-08-2025'),
('008', 'Información Geocientífica', 'geoscientificInformation', 'Información perteneciente a las ciencias de la Tierra. Ejemplos: procesos y fenómenos geofísicos, geología, minerales, ciencias relacionadas con la composición, estructura y origen de las rocas de la Tierra, riesgo sísmico, actividad volcánica, corrimiento de tierras, gravimetría, suelos, permafrost, hidrología y erosión', 1, 1, '15-08-2025'),
('009', 'Salud', 'health', 'Salud, servicios de salud, ecología humana y seguridad. Ejemplos: dolencias y enfermedades, factores que afectan a la salud, higiene, abusos de sustancias, salud mental y física, servicios de salud', 1, 1, '15-08-2025'),
('010', 'Cobertura de la Tierra con Mapas Básicos e Imágenes', 'imageBaseMapsEarthCover', 'Cartografía básica. Ejemplos: usos del suelo, mapas topográficos, imágenes, imágenes sin clasificar, anotaciones', 1, 1, '15-08-2025'),
('011', 'Inteligencia Militar', 'intelligenceMilitary', 'Redes militares, estructuras, actividades. Ejemplos: cuarteles, zonas de instrucción, transporte militar, alistamiento', 1, 1, '15-08-2025'),
('012', 'Aguas Interiores', 'inlandWaters', 'Fenómenos de agua interior, sistemas de drenaje y sus características. Ejemplos: ríos y glaciares, lagos de agua salada, planes de utilización de aguas, presas, corrientes, inundaciones, calidad de agua, planes hidrológicos', 1, 1, '15-08-2025'),
('013', 'Localización', 'location', 'Información posicional y servicios. Ejemplos: direcciones, redes geodésicas, puntos de control, servicios y zonas postales, nombres de lugares', 1, 1, '15-08-2025'),
('014', 'Océanos', 'oceans', 'Fenómenos y características de las aguas saladas (excluyendo las aguas interiores). Ejemplos: mareas, movimientos de marea, información de costa, arrecifes', 1, 1, '15-08-2025'),
('015', 'Planeamiento Catastral', 'planningCadastre', 'Información usada para tomar las acciones más apropiadas para el uso futuro de la tierra. Ejemplos: mapas de uso de suelo, mapas de zonas, levantamientos catastrales, propiedad del terreno', 1, 1, '15-08-2025'),
('016', 'Sociedad', 'society', 'Características de la sociedad y las culturas. Ejemplos: asentamientos, antropología, arqueología, educación, creencias tradicionales, modos y costumbres, datos demográficos, áreas y actividades recreativas, valoraciones de impacto social, crimen y justicia, información censal', 1, 1, '15-08-2025'),
('017', 'Estructuras', 'structure', 'Construcciones hechas por el hombre. Ejemplos: construcciones, museos, iglesias, fábricas, viviendas, monumentos, tiendas, torres', 1, 1, '15-08-2025'),
('018', 'Transporte', 'transportation', 'Medios y ayudas para transportar personas y mercancías. Ejemplos: carreteras, aeropuertos, pistas de aterrizaje, rutas, vías marítimas, túneles, cartas náuticas, localización de barcos o vehículos, cartas aeronáuticas, ferrocarriles', 1, 1, '15-08-2025'),
('019', 'Redes de Suministro', 'utilitiesCommunication', 'Redes de agua, de energía, de retirada de residuos, de infraestructura de comunicaciones y servicios. Ejemplos: hidroeléctricas, fuentes de energía geotermal, solar y nuclear, distribución y depuración de agua, recogida y almacenamiento de aguas residuales, distribución de gas y energía, comunicación de datos, telecomunicaciones, radio, redes de comunicación', 1, 1, '15-08-2025'); 

SELECT id, nombre, definicion FROM ide.def_categorias WHERE id_padre = 1;